#!/bin/bash
### BEGIN INIT INFO
# Provides:          olad-custom
# Required-Start:    $remote_fs $syslog olad
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Set inital olad DMX values.
# Description:       Set inital olad DMX values.
### END INIT INFO

start() {
  node /home/pi/workspace/artnet-client/startup.js
}

stop() {
  echo "nothing to do here"
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    start
    stop
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
